-- Generated by Prisma migrate diff. The final two constraints are reviewed
-- manual additions because Prisma cannot express a partial unique index or a
-- multi-column publication invariant in the schema DSL.

-- CreateTable
CREATE TABLE "verification_evidence_snapshots" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "application_id" UUID NOT NULL,
    "source_certificate_id" UUID NOT NULL,
    "upload_id" UUID NOT NULL,
    "title" VARCHAR(120) NOT NULL,
    "issuer" VARCHAR(120) NOT NULL,
    "issued_on" DATE NOT NULL,
    "expires_on" DATE,
    "moderation_status" "media_moderation_status" NOT NULL,
    "private_object_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verification_evidence_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "verification_evidence_application_created_idx" ON "verification_evidence_snapshots"("application_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "verification_evidence_application_certificate_key" ON "verification_evidence_snapshots"("application_id", "source_certificate_id");

-- AddForeignKey
ALTER TABLE "verification_evidence_snapshots" ADD CONSTRAINT "verification_evidence_snapshots_application_id_fkey" FOREIGN KEY ("application_id") REFERENCES "verification_applications"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Root categories require a separate partial unique index because PostgreSQL
-- treats NULL parent IDs as distinct in a normal composite unique index.
CREATE UNIQUE INDEX "service_categories_root_normalized_name_key"
ON "service_categories" ("normalized_name")
WHERE "parent_id" IS NULL;

-- Publishing a Professional is fail-closed unless the reviewed eligibility
-- assessment metadata is complete.
ALTER TABLE "professional_profiles"
  DROP CONSTRAINT "professional_profiles_service_eligibility_check",
  ADD CONSTRAINT "professional_profiles_service_eligibility_check"
    CHECK (
      NOT "is_service_active"
      OR (
        "verification_status" = 'APPROVED'
        AND "launch_eligibility_status" = 'ELIGIBLE'
        AND "eligibility_policy_version" IS NOT NULL
        AND "eligibility_reviewed_by_user_id" IS NOT NULL
        AND "eligibility_reviewed_at" IS NOT NULL
      )
    );
